accounts/urls.py
from django.urls import path
from .views import SignUpView, UserLoginView, UserPasswordReset, UserContactView
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views
app_name = 'accounts'
urlpatterns = [
    path('register/',SignUpView.as_view(), name='signup'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page="accounts:login"), name='logout'),
    path('contact_us/', UserContactView.as_view(), name='contactus'),
    path('password_reset', UserPasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name= 'password_reset_complete'),
    
]

base/urls.py
from django.urls import path
from .views import IndexView

app_name = 'base'
urlpatterns = [
    path('', IndexView.as_view(), name='index')
]

userAuthentication/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('accounts/', include('accounts.urls')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    profile_photo = models.ImageField(upload_to="profile/", blank =True, null=True)
    age = models.PositiveIntegerField(blank=True, null=True)

base/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = get_user_model()
        fields = ('first_name','last_name','username','email','age','profile_photo')

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name','last_name','username','email','age','profile_photo')

class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=50, label='',widget=forms.TextInput(attrs={"class":"form-control ","placeholder":"username",}))
    password = forms.CharField(max_length=50, label='', widget=forms.PasswordInput(attrs={"class":"form-control", "placeholder":"password"}))
    remember_me = forms.BooleanField(required=False)
    class Meta:
        model = get_user_model()
        fields = ["username","password","remember_me"]


class UserContactForm(forms.Form):
    first_name = forms.CharField(max_length=128, label='',widget=forms.TextInput(attrs={'placeholder':'First Name'}))
    last_name = forms.CharField(max_length=128, label='', widget=forms.TextInput(attrs={'placeholder':'Last Name'}))
    phone_number = forms.CharField(max_length=15, required=False, label='', widget=forms.TextInput(attrs={'placeholder':'Phone Number'}))
    email_address = forms.EmailField(max_length=100, label='', widget=forms.EmailInput(attrs={'placeholder':'Email Address'}))
    message = forms.CharField(max_length=5000, label='', widget=forms.Textarea(attrs={'placeholer':'Write your message here!'}))

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, LoginForm, UserContactForm
from django.views.generic.edit import CreateView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, PasswordResetView
from django.core.mail import send_mail
from django.views.generic import FormView
# Create your views here.
class SignUpView(SuccessMessageMixin, CreateView):
    form_class = CustomUserCreationForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('base:index')

    def get_success_message(self, cleaned_data):
        print(cleaned_data)
        return "Registeration Successfull"
    #Using dispatch to restrict register page when user is logged in
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('base:index')
        return super(SignUpView, self).dispatch(request, *args, **kwargs)


class UserLoginView(SuccessMessageMixin, LoginView):
    form_class = LoginForm
    template_name = "accounts/login.html"       

    def get_success_message(self, cleaned_data):
        print(cleaned_data)
        return "Logged In Successfull"

    def form_valid(self, form):
        remember_me = form.cleaned_data.get('remember_me')
        if not remember_me:
            self.request.session.set_expiry(0)#Automatically closes the session after browser is closed
            self.request.session.modified = True#set modified data in session to be stored
        return super(UserLoginView, self).form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('base:index')
        return super(UserLoginView, self).dispatch(request, *args, **kwargs)


class UserPasswordReset(SuccessMessageMixin, PasswordResetView):
    template_name = 'accounts/password_reset.html'
    email_template_name = 'accounts/password_reset_email.html'
    success_url = reverse_lazy("accounts:password_reset_done")

class UserContactView(SuccessMessageMixin, FormView):
    form_class = UserContactForm
    template_name = 'accounts/contactus.html'
    success_url = reverse_lazy('base:index')
    def form_valid(self, form):
        send_mail(
            subject = f"Message from {form.cleaned_data['first_name']} {form.cleaned_data['last_name']}",
            message = form.cleaned_data['message'],
            from_email=form.cleaned_data['email_address'],
            recipient_list=['ishan.shrestha356@gmail.com',]
        )
        return super(UserContactView, self).form_valid(form)
        
    
    def get_success_message(self, cleaned_data):
        print(cleaned_data)
        return "Message Successfully Sent"

base/views.py
from django.shortcuts import render
from django.views import View

# Create your views here.
class IndexView(View):
    template_name = 'base/index.html'
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, context={})

accounts/templates/accounts/contactus.html
{% extends 'base/base.html' %}
{% block title %}Contact Us{% endblock title %}
{% block body %}
<div class="container mt-5">
    <h1>Contact Us</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Contact Us" class="btn btn-secondary text-white">
    </form>
</div>
{% endblock body %}

accounts/templates/accounts/login.html
{% extends 'base/base.html' %}
{% block title %}Home{% endblock title %}
{% block body %}
<div class="container mt-5">
    <h1>Login</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login" class="btn btn-secondary text-white">
    </form>
    <a href="{% url 'social:begin' 'github' %}" class='text-white'><button class="btn btn-secondary">Login With GitHub</button></a>
    <a href="{% url 'social:begin' 'google-oauth2' %}" class="text-white"><button class="btn btn-secondary">Login With Google</button></a>
    <br>
    <a href="{% url 'accounts:password_reset' %}" class="text-white"><button class="btn btn-secondary">Forget Password</button></a>
</div>
{% endblock body %}

accounts/templates/accounts/password_reset.html
{% extends 'base/base.html' %}
{% block title %}Forget Password{% endblock title %}
{% block body %}
<div class="container mt-5">
    <h1>Forget Password</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send Reset Link" class="btn btn-secondary text-white">
    </form>
</div>
{% endblock body %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base/base.html' %}
{% block title %}Success{% endblock title %}
{% block body %}
<div class="container mt-5">
    <h1>Password Reset Successfull</h1>
</div>
{% endblock body %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base/base.html' %}
{% block title %}Reset Password{% endblock title %}
{% block body %}
<div class="container mt-5">
    <h1>Reset Password</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Reset" class="btn btn-secondary text-white">
    </form>
</div>
{% endblock body %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base/base.html' %}
{% block title %}Forget Password{% endblock title %}
{% block body %}
<div class="container mt-5">
    <h1>Email Successfully Sent</h1>
</div>
{% endblock body %}

accounts/templates/accounts/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}
	
{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}
	
{% endautoescape %}

accounts/templates/accounts/signup.html
{% extends 'base/base.html' %}
{% block title %}Home{% endblock title %}
{% block body %}
<div class="container mt-5">
    <h1>Register</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
</div>
{% endblock body %}

base/templates/base/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'base/navbar.html' %}
    {% include 'base/messages.html' %}
    {% block body %}    
    {% endblock body %}    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

base/templates/base/index.html
{% extends 'base/base.html' %}
{% block title %}Home{% endblock title %}
{% block body %}
<div class="container mt-5">
    <h1>Featiures of this django template</h1>
    <ul>
        <li>Custom User Model</li>
        <li>Configured for static files and media files</li>
        <li>Login and Logout System</li>
        <li>User Profile and profile update</li>
        <li>Production quality email smtp configuration</li>
        <li>Password Reset System</li>
        <li>Social App Authentication</li>
        <li>Contact Us system</li>
        <li>Use of django crispy forms</li>
    </ul>

</div>
{% endblock body %}

base/templates/base/messages.html
{% if messages %}
<div class="alert alert-warning">
    {% for message in messages %}
    {{ message }}
    {% endfor %}
</div>
{% endif %}

base/templates/base/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'base:index' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="#">{{ user.username|title }}<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:logout' %}">Logout<span class="sr-only">(current)</span></a>
        </li>
        {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:login' %}">Login<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:signup' %}">Register<span class="sr-only">(current)</span></a>
        </li>
        {% endif %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:contactus' %}">Contact Us<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>